matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: trues
  dictionary:
    wordlists:
    - .github/.config/dictionaries/.wordlist.txt
    encoding: utf-8
    output: .wordlist.dic
  pipeline:
  - pyspelling.filters.text
  sources:
  - '*.md'
  default_encoding: utf-8